package client

import (
	"context"
	"net/http"
	"time"

	"github.com/famomatic/ytv1/internal/innertube"
)

// Config holds configuration for the YouTube client.
type Config struct {
	// HTTPClient is the client used for making requests.
	// If nil, http.DefaultClient is used.
	HTTPClient *http.Client

	// ProxyURL is the optional proxy URL to use for requests.
	// If HTTPClient is provided, this field is ignored.
	ProxyURL string

	// PoTokenProvider is the provider for PO Tokens.
	// If nil, PO Tokens will not be injected, which may cause throttling or errors.
	PoTokenProvider innertube.PoTokenProvider

	// PoTokenFetchPolicy overrides POT enforcement per streaming protocol.
	// Supported values: required|recommended|never.
	PoTokenFetchPolicy map[innertube.VideoStreamingProtocol]innertube.PoTokenFetchPolicy

	// VisitorData is the "VISITOR_INFO1_LIVE" cookie value.
	// Use this to persist sessions or emulate a specific user context.
	VisitorData string

	// PlayerJSBaseURL overrides player JS fetch host (default: https://www.youtube.com).
	PlayerJSBaseURL string

	// PlayerJSUserAgent overrides player JS fetch User-Agent.
	// If empty, package fallback is used.
	PlayerJSUserAgent string

	// PlayerJSHeaders are additional headers for player JS fetches.
	PlayerJSHeaders http.Header

	// PlayerJSPreferredLocale controls canonical locale for player JS fetch path.
	// Default is "en_US". Fetch falls back to the original watch-page locale path.
	PlayerJSPreferredLocale string

	// ClientOverrides sets Innertube client trial order (e.g. "web", "ios", "android").
	// If empty, package defaults are used.
	ClientOverrides []string

	// AppendFallbackOnClientOverrides keeps fallback-client auto append enabled even
	// when ClientOverrides is explicitly provided.
	// Default is false: explicit override mode disables auto fallback append.
	AppendFallbackOnClientOverrides bool

	// DisableDynamicAPIKeyResolution disables watch-page ytcfg API key extraction.
	// Default is false (dynamic resolution enabled).
	DisableDynamicAPIKeyResolution bool

	// RequestHeaders are applied to package-level outgoing HTTP requests.
	RequestHeaders http.Header

	// RequestTimeout applies a default timeout when incoming context has no deadline.
	// Zero means no additional timeout.
	RequestTimeout time.Duration

	// ClientSkip excludes specific Innertube clients from selection.
	ClientSkip []string

	// DisableFallbackClients disables automatic fallback-client append behavior.
	DisableFallbackClients bool

	// MetadataTransport configures retry/backoff for Innertube metadata requests.
	MetadataTransport MetadataTransportConfig

	// MP3Transcoder handles optional stream->mp3 conversion in Download(mode=mp3).
	// If nil, mp3 mode returns ErrMP3TranscoderNotConfigured.
	MP3Transcoder MP3Transcoder

	// DownloadTransport configures retry/backoff behavior for stream downloads.
	DownloadTransport DownloadTransportConfig

	// Muxer handles optional video+audio merging in Download(options.Merge=true).
	// If nil, merge operations will warn and fallback to pre-muxed formats.
	Muxer Muxer

	// Logger receives non-fatal package warnings (optional).
	// If nil, warnings are suppressed.
	Logger Logger

	// SessionCacheTTL expires in-memory video sessions after this duration.
	// Zero disables TTL-based expiration.
	SessionCacheTTL time.Duration

	// SessionCacheMaxEntries bounds in-memory video session count (LRU eviction).
	// Zero or negative means unbounded.
	SessionCacheMaxEntries int

	// SubtitlePolicy controls default subtitle track selection behavior.
	SubtitlePolicy SubtitlePolicy
}

// SubtitlePolicy controls subtitle selection when language is not explicitly specified.
type SubtitlePolicy struct {
	PreferredLanguageCode string
	FallbackLanguageCodes []string
	PreferAutoGenerated   bool
}

// Muxer defines the interface for media muxing operations.
type Muxer interface {
	Available() bool
	Merge(ctx context.Context, videoPath, audioPath, outputPath string) error
}

// DownloadTransportConfig controls retry/backoff behavior for direct stream downloads.
type DownloadTransportConfig struct {
	MaxRetries       int
	InitialBackoff   time.Duration
	MaxBackoff       time.Duration
	RetryStatusCodes []int
	EnableChunked    bool
	ChunkSize        int64
	MaxConcurrency   int
}

// MetadataTransportConfig controls retry/backoff for Innertube player metadata requests.
type MetadataTransportConfig struct {
	MaxRetries       int
	InitialBackoff   time.Duration
	MaxBackoff       time.Duration
	RetryStatusCodes []int
}

func (c Config) ToInnerTubeConfig() innertube.Config {
	disableFallback := c.DisableFallbackClients
	if !disableFallback && len(c.ClientOverrides) > 0 && !c.AppendFallbackOnClientOverrides {
		disableFallback = true
	}

	return innertube.Config{
		HTTPClient:                    c.HTTPClient,
		ProxyURL:                      c.ProxyURL,
		PoTokenProvider:               c.PoTokenProvider,
		PoTokenFetchPolicy:            c.PoTokenFetchPolicy,
		VisitorData:                   c.VisitorData,
		PlayerJSBaseURL:               c.PlayerJSBaseURL,
		PlayerJSUserAgent:             c.PlayerJSUserAgent,
		PlayerJSHeaders:               c.PlayerJSHeaders,
		PlayerJSPreferredLocale:       c.PlayerJSPreferredLocale,
		ClientOverrides:               c.ClientOverrides,
		ClientSkip:                    c.ClientSkip,
		RequestHeaders:                c.RequestHeaders,
		RequestTimeout:                c.RequestTimeout,
		DisableFallbackClients:        disableFallback,
		MetadataTransport:             innertube.MetadataTransportConfig(c.MetadataTransport),
		EnableDynamicAPIKeyResolution: !c.DisableDynamicAPIKeyResolution,
	}
}
