package client

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"strings"
	"testing"

	"github.com/famomatic/ytv1/internal/innertube"
)

func TestGetSubtitleTracks(t *testing.T) {
	videoID := "jNQXAC9IVRw"
	c := testClientWithSession(videoID, innertube.Format{Itag: 140, URL: "https://example.com/a"}, testPlayerJS())
	c.sessions[videoID] = videoSession{
		Response: &innertube.PlayerResponse{
			VideoDetails: innertube.VideoDetails{VideoID: videoID},
			Captions: innertube.Captions{
				PlayerCaptionsTracklistRenderer: innertube.PlayerCaptionsTracklistRenderer{
					CaptionTracks: []innertube.CaptionTrack{
						{
							BaseURL:      "https://caption.local/api?lang=en",
							LanguageCode: "en",
							VssID:        ".en",
							Name:         innertube.LangText{SimpleText: "English"},
						},
						{
							BaseURL:      "https://caption.local/api?lang=ko",
							LanguageCode: "ko",
							VssID:        "a.ko",
							Kind:         "asr",
							Name:         innertube.LangText{SimpleText: "Korean (auto-generated)"},
						},
					},
				},
			},
		},
		PlayerURL: "/s/player/test/base.js",
	}

	tracks, err := c.GetSubtitleTracks(context.Background(), videoID)
	if err != nil {
		t.Fatalf("GetSubtitleTracks() error = %v", err)
	}
	if len(tracks) != 2 {
		t.Fatalf("tracks len=%d, want 2", len(tracks))
	}
	if tracks[1].LanguageCode != "ko" || !tracks[1].AutoGenerated {
		t.Fatalf("unexpected second track: %+v", tracks[1])
	}
}

func TestGetTranscript(t *testing.T) {
	videoID := "jNQXAC9IVRw"
	httpClient := &http.Client{
		Transport: roundTripFunc(func(r *http.Request) (*http.Response, error) {
			if strings.HasPrefix(r.URL.Host, "caption.local") {
				body := `<transcript><text start="0.0" dur="1.2">hello</text><text start="1.2" dur="0.8">world</text></transcript>`
				return &http.Response{
					StatusCode: http.StatusOK,
					Header:     make(http.Header),
					Body:       io.NopCloser(bytes.NewBufferString(body)),
				}, nil
			}
			t.Fatalf("unexpected request: %s", r.URL.String())
			return nil, nil
		}),
	}
	c := &Client{
		config: Config{HTTPClient: httpClient},
		sessions: map[string]videoSession{
			videoID: {
				Response: &innertube.PlayerResponse{
					VideoDetails: innertube.VideoDetails{VideoID: videoID},
					Captions: innertube.Captions{
						PlayerCaptionsTracklistRenderer: innertube.PlayerCaptionsTracklistRenderer{
							CaptionTracks: []innertube.CaptionTrack{
								{
									BaseURL:      "https://caption.local/api?lang=en",
									LanguageCode: "en",
									Name:         innertube.LangText{SimpleText: "English"},
								},
							},
						},
					},
				},
				PlayerURL: "/s/player/test/base.js",
			},
		},
	}

	got, err := c.GetTranscript(context.Background(), videoID, "en")
	if err != nil {
		t.Fatalf("GetTranscript() error = %v", err)
	}
	if len(got.Entries) != 2 {
		t.Fatalf("entries len=%d, want 2", len(got.Entries))
	}
	if got.Entries[0].Text != "hello" {
		t.Fatalf("entry[0] text=%q, want hello", got.Entries[0].Text)
	}
}

func TestGetPlaylist(t *testing.T) {
	html := `<html><script>var ytInitialData = {"metadata":{"playlistMetadataRenderer":{"title":"My Playlist"}},"contents":[{"playlistVideoRenderer":{"videoId":"aaaaaaaaaaa","title":{"simpleText":"one"},"shortBylineText":{"runs":[{"text":"author1"}]},"lengthText":{"simpleText":"1:00"}}},{"playlistVideoRenderer":{"videoId":"bbbbbbbbbbb","title":{"runs":[{"text":"two"}]},"shortBylineText":{"runs":[{"text":"author2"}]},"lengthText":{"simpleText":"2:00"}}}]};</script></html>`
	httpClient := &http.Client{
		Transport: roundTripFunc(func(r *http.Request) (*http.Response, error) {
			if r.Method == http.MethodGet && r.URL.Path == "/playlist" {
				return &http.Response{
					StatusCode: http.StatusOK,
					Header:     make(http.Header),
					Body:       io.NopCloser(bytes.NewBufferString(html)),
				}, nil
			}
			t.Fatalf("unexpected request: %s", r.URL.String())
			return nil, nil
		}),
	}

	c := &Client{config: Config{HTTPClient: httpClient}}
	got, err := c.GetPlaylist(context.Background(), "https://www.youtube.com/playlist?list=PL1234567890")
	if err != nil {
		t.Fatalf("GetPlaylist() error = %v", err)
	}
	if got.Title != "My Playlist" {
		t.Fatalf("title=%q, want %q", got.Title, "My Playlist")
	}
	if len(got.Items) != 2 {
		t.Fatalf("items len=%d, want 2", len(got.Items))
	}
}

func TestExtractPlaylistID(t *testing.T) {
	id, err := ExtractPlaylistID("https://www.youtube.com/watch?v=jNQXAC9IVRw&list=PLabc123")
	if err != nil {
		t.Fatalf("ExtractPlaylistID() error = %v", err)
	}
	if id != "PLabc123" {
		t.Fatalf("ExtractPlaylistID()=%q, want %q", id, "PLabc123")
	}
}
