package client

// VideoInfo is the package-level metadata result.
type VideoInfo struct {
	ID              string
	Title           string
	Author          string
	Formats         []FormatInfo
	DashManifestURL string
	HLSManifestURL  string
}

// FormatInfo is the normalized public format model.
type FormatInfo struct {
	Itag         int
	URL          string
	MimeType     string
	Protocol     string
	HasAudio     bool
	HasVideo     bool
	Bitrate      int
	Width        int
	Height       int
	FPS          int
	Ciphered     bool
	Quality      string
	QualityLabel string
}

// SubtitleTrack describes one subtitle/caption track.
type SubtitleTrack struct {
	LanguageCode  string
	Name          string
	BaseURL       string
	VssID         string
	Kind          string
	AutoGenerated bool
}

// TranscriptEntry is one timed caption segment.
type TranscriptEntry struct {
	StartSec float64
	DurSec   float64
	Text     string
}

// Transcript is a normalized transcript payload.
type Transcript struct {
	VideoID      string
	LanguageCode string
	Name         string
	Entries      []TranscriptEntry
}

// PlaylistItem is one entry in a playlist.
type PlaylistItem struct {
	VideoID         string
	Title           string
	Author          string
	DurationSeconds string
}

// PlaylistInfo is a normalized playlist payload.
type PlaylistInfo struct {
	ID    string
	Title string
	Items []PlaylistItem
}
