package cli

import (
	"context"
	"testing"
	"time"
)

func TestToClientConfig_StaticPoTokenProvider(t *testing.T) {
	cfg, err := ToClientConfig(Options{
		PoToken: "token-abc",
	})
	if err != nil {
		t.Fatalf("ToClientConfig() error = %v", err)
	}
	if cfg.PoTokenProvider == nil {
		t.Fatalf("expected PoTokenProvider to be configured")
	}
	token, err := cfg.PoTokenProvider.GetToken(context.Background(), "web")
	if err != nil {
		t.Fatalf("PoTokenProvider.GetToken() error = %v", err)
	}
	if token != "token-abc" {
		t.Fatalf("token = %q, want %q", token, "token-abc")
	}
}

func TestToClientConfig_EmptyPoTokenDoesNotConfigureProvider(t *testing.T) {
	cfg, err := ToClientConfig(Options{
		PoToken: "   ",
	})
	if err != nil {
		t.Fatalf("ToClientConfig() error = %v", err)
	}
	if cfg.PoTokenProvider != nil {
		t.Fatalf("expected PoTokenProvider to be nil for empty override")
	}
}

func TestToClientConfig_RetryOverrides(t *testing.T) {
	cfg, err := ToClientConfig(Options{
		DownloadRetries: 4,
		RetrySleepMS:    750,
	})
	if err != nil {
		t.Fatalf("ToClientConfig() error = %v", err)
	}
	if cfg.DownloadTransport.MaxRetries != 4 || cfg.MetadataTransport.MaxRetries != 4 {
		t.Fatalf("retry overrides not applied: download=%d metadata=%d", cfg.DownloadTransport.MaxRetries, cfg.MetadataTransport.MaxRetries)
	}
	wantBackoff := 750 * time.Millisecond
	if cfg.DownloadTransport.InitialBackoff != wantBackoff || cfg.MetadataTransport.InitialBackoff != wantBackoff {
		t.Fatalf("backoff overrides not applied: download=%s metadata=%s", cfg.DownloadTransport.InitialBackoff, cfg.MetadataTransport.InitialBackoff)
	}
}

func TestToClientConfig_SubtitlePolicyFromFlags(t *testing.T) {
	cfg, err := ToClientConfig(Options{
		SubLangs:      "ko, en ,ko",
		WriteAutoSubs: true,
	})
	if err != nil {
		t.Fatalf("ToClientConfig() error = %v", err)
	}
	if cfg.SubtitlePolicy.PreferredLanguageCode != "ko" {
		t.Fatalf("preferred language=%q, want ko", cfg.SubtitlePolicy.PreferredLanguageCode)
	}
	if len(cfg.SubtitlePolicy.FallbackLanguageCodes) != 1 || cfg.SubtitlePolicy.FallbackLanguageCodes[0] != "en" {
		t.Fatalf("fallback languages=%v, want [en]", cfg.SubtitlePolicy.FallbackLanguageCodes)
	}
	if !cfg.SubtitlePolicy.PreferAutoGenerated {
		t.Fatalf("PreferAutoGenerated=%v, want true", cfg.SubtitlePolicy.PreferAutoGenerated)
	}
}
